sns/Package.md

Update Package overview

---

README.md

Update readme with overview

---

README.md

Update build status in Readme.md

---

.github/workflows/ci.yml
.github/workflows/daily-build.yml
.github/workflows/pull-request.yml
.github/workflows/release.yml
README.md
sns/Package.md
sns/client.bal
sns/tests/test.bal

Update test cases to remove build failure

---

.github/workflows/ci.yml
.github/workflows/daily-build.yml
.github/workflows/pull-request.yml
.github/workflows/release.yml
README.md
sns/Dependencies.toml

Related https://github.com/ballerina-platform/ballerina-extended-library/issues/128
One line release note: 
- Add slbeta4 migration changes
**Test Configuration**:
* Ballerina Version: Ballerina swan lake beta 4
* Operating System: Ubuntu (Linux)
* Java SDK: Java 11

Add slbeta4 migration changes

---

README.md
build.gradle
gradle.properties
sns/Ballerina.toml
sns/Dependencies.toml
sns/Package.md

- Bump version to `1.1.0`
- Update Ballerina version to `SLBeta6` in Package.md 
- Regenerate Dependencies.toml with `SLBeta6`
- Add `distribution = "slbeta6"` in Ballerina.toml

Prepare for 1.1.0 release with SLBeta6

---

sns/Dependencies.toml

- Update Dependencies.toml with latest standard library versions

Re-generate Dependencies.toml with latest pack

---

gradle.properties
sns/Ballerina.toml
sns/Dependencies.toml
sns/Package.md

Prepare for 1.2.0 release

---

.github/workflows/ci.yml
.github/workflows/dev-staging-release.yml
.github/workflows/release.yml
sns/Module.md
sns/client.bal
sns/data_mappings.bal
sns/error.bal
sns/external.bal
sns/samples/CreateTopic.bal
sns/samples/DeleteTopic.bal
sns/samples/Publish.bal
sns/samples/Subscribe.bal
sns/tests/test.bal
sns/types.bal
sns/utils.bal

- Fix https://github.com/ballerina-platform/ballerina-extended-library/issues/424
- Fix https://github.com/ballerina-platform/ballerina-extended-library/issues/425
- Add workflow to release to staging and dev https://github.com/ballerina-platform/ballerina-extended-library/issues/130

Update samples and improve coverage

---

sns/Ballerina.toml
sns/Dependencies.toml
sns/Package.md
sns/client.bal
sns/config-types.bal
sns/constants.bal
sns/utils.bal

- Alter ConnectionConfig record 
- Bump connector version and ballerina version in Ballerina.toml
- Bump ballerina version in Package.md
- Update Dependencies.toml with Ballerina 2201.2.0

Alter ConnectionConfig record

---

README.md
sns/Package.md

$Subject
Fixes # https://github.com/ballerina-platform/ballerina-extended-library/issues/474

Update Slack channel occurrences with Discord

---

sns/Ballerina.toml
sns/Dependencies.toml
sns/Package.md

$Subject
Fixes # https://github.com/ballerina-platform/ballerina-extended-library/issues/475

Update to Ballerina version 2201.3.0

---

ballerina/Module.md
ballerina/tests/test.bal
ballerina/utils.bal
examples/CreateTopic.bal

$subject.
Fixes # (issue)
One line release note: 
- One line describing the feature/improvement/fix made by this PR 
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
**Test Configuration**:
* Ballerina Version:
* Operating System:
* Java SDK:

Fix compatibility issues with update 8

---

.github/workflows/build-with-bal-test-native.yml
.github/workflows/ci.yml
.github/workflows/daily-build.yml
.github/workflows/dev-staging-release.yml
.github/workflows/dev-stg-release.yml
.github/workflows/pull-request.yml
.github/workflows/release.yml
ballerina/Ballerina.toml
ballerina/Package.md

$subject
Fixes # (issue)
Related Pull Requests (remove if not relevant)
- Pull request 1
- Pull request 2
One line release note: 
- One line describing the feature/improvement/fix made by this PR 
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
**Test Configuration**:
* Ballerina Version:
* Operating System:
* Java SDK:

Migrate AWS.SNS connector to SL Update 8

---

.github/workflows/build-with-bal-test-native.yml
.github/workflows/ci.yml
.github/workflows/daily-build.yml
.github/workflows/pull-request.yml
ballerina/Dependencies.toml
ballerina/tests/endpoint-tests.bal
ballerina/tests/init.bal
ballerina/tests/phone-number-tests.bal
ballerina/tests/platform-application-tests.bal
ballerina/tests/publish-tests.bal
ballerina/tests/sms-attributes-tests.bal
ballerina/tests/sms-sandbox-tests.bal
ballerina/tests/subscription-tests.bal
ballerina/tests/tag-tests.bal
ballerina/tests/topics-tests.bal
ballerina/utils.bal

Enable test cases

---

ballerina/tests/sms-sandbox-tests.bal

$subject
This test case relies on

Fix listSMSSandboxPhoneNumbers test case

---

examples/football-scores/Ballerina.toml
examples/football-scores/Dependencies.toml
examples/football-scores/main.bal
examples/weather-alert/Ballerina.toml

Add local central dependencies

---

.github/workflows/build-with-bal-test-graalvm.yml
.github/workflows/trivy-scan.yml

Skip the examples build from the trivy scan and graalvm build

---

build.gradle
examples/build.gradle
settings.gradle

Enable examples in the sns connector build

---

.github/workflows/build-with-bal-test-graalvm.yml
.github/workflows/ci.yml
.github/workflows/daily-build.yml
.github/workflows/dev-stage-release.yml
.github/workflows/pull-request.yml
.github/workflows/release.yml
.github/workflows/trivy-scan.yml

Update workflow template links

---

.github/workflows/ci.yml
.github/workflows/daily-build.yml
.github/workflows/dev-stage-release.yml
.github/workflows/release.yml

Update the workflows to disable examples build

---

ballerina/client.bal
ballerina/data_mappings.bal
ballerina/tests/subscription-tests.bal
ballerina/utils.bal
ballerina/validators.bal

Refactor the code

---

ballerina/validators.bal

Fix the test failure

---

.gitignore

Ignore the deb files in gitignore

---

.gitignore

Ignore the target directory

---

.github/workflows/release.yml

Skip the examples build from the release build

---

build.gradle
gradle.properties

Update the lang version in the project

---

ballerina/build.gradle
gradle.properties

Update the gradle plugin version

---

.github/workflows/trivy-scan.yml

Remove the invalid test flag

---

README.md

Update GraalVM check badge

---

examples/README.md

Update example README file

---

.github/workflows/pull-request.yml
README.md
ballerina/Ballerina.toml
ballerina/Dependencies.toml
build-config/resources/Ballerina.toml
gradle.properties

Migrate to Java 21
